apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-store
helmCharts:
  - name: tenant
    repo: https://operator.min.io
    version: 6.0.2
    releaseName: tenant
    namespace: minio-store
    includeCRDs: false
    valuesFile: values.yaml

resources:
  - configs/cert.yaml
  - servicemonitor.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    v1.min.io/tenant: galah
#TODO: Gen secrets from env file
secretGenerator:
  - name: minio-env
    files:
      - configs/config.env
  - name: minio-user
    envs:
        - configs/.env.minio-user
